### PR TITLE
Upgrade to v2

### PR DESCRIPTION
**Pull request by Alex-D**
Hi!

I'm the Trumbowyg developer. @snvl1993 requested me to switch from this repo to his repo because this one is not up to date.

Do want to maintain your repo or I switch to @snvl1993 's repo on the Trumbowyg page?

I think it would be better to keep a single rails repository up to date rather multiple forks.

Hope you ( @TikiTDO and @snvl1993 ) are OK with that philosophy.

Thanks for your work :)

### CODE REVIEW

**Comment by TikiTDO** [comment]
Hey, I don't really use this gem much anymore. I'll give you access to this repo do you can proceed how you want to.

**Comment by TikiTDO** [comment]
@Alex-D Please let me know your rubygems username. I will add you as an owner so you can push new releases.

Also, since you are the owner of the original lib, it might actually be easier to include the ruby specific stuff as a subdirectory of your repo. That way you could tie together and automate the entire release process. Let me know if you want to do that and I will happily help.

**Comment by Alex-D** [comment]
That could be a great idea in fact. But, do you think it's not messy to have all 3rd party in the main repo?

**Comment by snvl1993** [comment]
Hi!

I am new in community development and should have made a pull request as soon as I commit the changes. I am completely OK with moving changes to origin repository.

But I have created a gem trumbowyg2_rails and push it to the rubygems. I'll be grateful if you give me some advice what to do with it (now it near 400 downloads) and not to do any damage to users?

**Comment by TikiTDO** [comment]
@Alex-D I'm not sure if this sort of lib can even be considered 3rd party. It's just a recipe for wrapping a your library in a gem, little different from the bower.json. If done properly it would be a gemspec in your root directory, something like a src/rubygem directory to hold the engine definition, and an extra step in your release process to run `gem build` and `gem push`. Not sure if you automate your releases right now, but if so it could be effectively transparent.

If you're interested in taking possession of this process then I could write it all up, and submit a pull request to the Trumbowyg repo. That would also ensure that the ruby version would always track the latest version, which is a lot less likely to happen with a third party maintainer.

**Comment by TikiTDO** [comment]
@snvl1993 Generally best practice for community projects is to submit a pull request with the required update, or at least creating an issue asking for an update. Occasionally you might run into a truly abandoned project with AWOL developers, but it's always a good idea to try anyway. In this case I simply haven't been following the original project because I'm not currently using it in any projects.

Creating a new gem just creates confusion about which version to use, and runs the risk of leaving some users out of the loop. Unfortunately if your gem has already been released and downloaded there is not much to do. People are already using both gems, so removing either will break someone's application.

**Pull request merged**
